CREATE DATABASE COMERCIO
GO

USE COMERCIO
GO

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(30) NOT NULL,
    SOBRENOME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    NASCIMENTO DATE NOT NULL
);
GO

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY IDENTITY(1,1),
    RUA VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    REGIAO VARCHAR(20) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    CONSTRAINT FK_ENDERECO_CLIENTE
        FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);
GO

CREATE TABLE VENDEDOR(
    IDVENDEDOR INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(30) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    ID_GERENTE INT NULL,
    CONSTRAINT FK_VENDEDOR_GERENTE
        FOREIGN KEY (ID_GERENTE) REFERENCES VENDEDOR(IDVENDEDOR)
);
GO

CREATE TABLE CATEGORIA(
    IDCATEGORIA INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(30) NOT NULL
);
GO

CREATE TABLE FORNECEDOR(
    IDFORNECEDOR INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(50) NOT NULL
);
GO

CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY IDENTITY(1,1),
    PRODUTO VARCHAR(100) NOT NULL,
    VALOR NUMERIC(10,2) NOT NULL,
    CUSTO_MEDIO NUMERIC(10,2) NULL,
    ID_CATEGORIA INT,
    ID_FORNECEDOR INT,
    CONSTRAINT FK_PRODUTO_CATEGORIA
        FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA),
    CONSTRAINT FK_PRODUTO_FORNECEDOR
        FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
);
GO

CREATE TABLE FORMA_PAGAMENTO(
    IDFORMA INT PRIMARY KEY IDENTITY(1,1),
    FORMA VARCHAR(40) NOT NULL
);
GO

CREATE TABLE NOTA_FISCAL(
    IDNOTA INT PRIMARY KEY IDENTITY(1000,10),
    DATA DATE NOT NULL,
    TOTAL NUMERIC(10,2) NOT NULL,
    ID_FORMA INT,
    ID_CLIENTE INT,
    ID_VENDEDOR INT,
    CONSTRAINT FK_NOTA_FORMA
        FOREIGN KEY (ID_FORMA) REFERENCES FORMA_PAGAMENTO(IDFORMA),
    CONSTRAINT FK_NOTA_CLIENTE
        FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE),
    CONSTRAINT FK_NOTA_VENDEDOR
        FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(IDVENDEDOR)
);
GO

CREATE TABLE ITEM_NOTA(
    IDITEMNOTA INT PRIMARY KEY IDENTITY(1,1),
    ID_PRODUTO INT NOT NULL,
    ID_NOTA_FISCAL INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR_UNITARIO NUMERIC(10,2) NOT NULL,
    TOTAL NUMERIC(10,2) NOT NULL,
    CONSTRAINT FK_ITEM_NOTA_PRODUTO
        FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO),
    CONSTRAINT FK_ITEM_NOTA_NOTA
        FOREIGN KEY (ID_NOTA_FISCAL) REFERENCES NOTA_FISCAL(IDNOTA),
    CONSTRAINT CK_ITEM_NOTA_QUANTIDADE
        CHECK (QUANTIDADE > 0),
    CONSTRAINT CK_ITEM_NOTA_TOTAL
        CHECK (TOTAL >= 0)
);
GO