-- CONSULTAS BASE DO PROJETO

USE COMERCIO;
GO
    
-- CLIENTES COM CIDADE, ESTADO E REGIÃO

SELECT 
    C.IDCLIENTE,
    C.NOME,
    C.SOBRENOME,
    C.EMAIL,
    C.SEXO,
    C.NASCIMENTO,
    E.RUA,
    E.CIDADE,
    E.ESTADO,
    E.REGIAO
FROM CLIENTE C
INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE;
GO
    
-- PRODUTOS COM CATEGORIA E FORNECEDOR

SELECT 
    P.IDPRODUTO,
    P.PRODUTO,
    P.VALOR,
    P.CUSTO_MEDIO,
    C.NOME AS CATEGORIA,
    F.NOME AS FORNECEDOR
FROM PRODUTO P
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
INNER JOIN FORNECEDOR F
    ON P.ID_FORNECEDOR = F.IDFORNECEDOR;
GO
    
-- NOTAS FISCAIS COM CLIENTE, VENDEDOR E FORMA DE PAGAMENTO

SELECT 
    N.IDNOTA,
    N.DATA,
    N.TOTAL,
    C.NOME + ' ' + C.SOBRENOME AS CLIENTE,
    V.NOME AS VENDEDOR,
    FP.FORMA AS FORMA_PAGAMENTO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C
    ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN VENDEDOR V
    ON N.ID_VENDEDOR = V.IDVENDEDOR
INNER JOIN FORMA_PAGAMENTO FP
    ON N.ID_FORMA = FP.IDFORMA;
GO
    
-- ITENS DAS NOTAS COM PRODUTO E VALOR TOTAL DO ITEM

SELECT 
    I.IDITEMNOTA,
    I.ID_NOTA_FISCAL,
    P.PRODUTO,
    I.QUANTIDADE,
    I.VALOR_UNITARIO,
    I.TOTAL
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO;
GO
    
-- VISÃO COMPLETA DA VENDA

SELECT 
    N.IDNOTA,
    N.DATA,
    C.NOME + ' ' + C.SOBRENOME AS CLIENTE,
    E.CIDADE,
    E.ESTADO,
    V.NOME AS VENDEDOR,
    FP.FORMA AS FORMA_PAGAMENTO,
    P.PRODUTO,
    CAT.NOME AS CATEGORIA,
    I.QUANTIDADE,
    I.VALOR_UNITARIO,
    I.TOTAL AS TOTAL_ITEM,
    N.TOTAL AS TOTAL_NOTA
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C
    ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN VENDEDOR V
    ON N.ID_VENDEDOR = V.IDVENDEDOR
INNER JOIN FORMA_PAGAMENTO FP
    ON N.ID_FORMA = FP.IDFORMA
INNER JOIN ITEM_NOTA I
    ON N.IDNOTA = I.ID_NOTA_FISCAL
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA CAT
    ON P.ID_CATEGORIA = CAT.IDCATEGORIA;
GO
    
--  TOTAL DE NOTAS POR CLIENTE

SELECT 
    C.IDCLIENTE,
    C.NOME + ' ' + C.SOBRENOME AS CLIENTE,
    COUNT(N.IDNOTA) AS QTD_NOTAS,
    SUM(N.TOTAL) AS TOTAL_GASTO
FROM CLIENTE C
INNER JOIN NOTA_FISCAL N
    ON C.IDCLIENTE = N.ID_CLIENTE
GROUP BY 
    C.IDCLIENTE,
    C.NOME,
    C.SOBRENOME
ORDER BY TOTAL_GASTO DESC;
GO
    
-- TOTAL VENDIDO POR CATEGORIA

SELECT 
    CAT.NOME AS CATEGORIA,
    SUM(I.TOTAL) AS TOTAL_VENDIDO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA CAT
    ON P.ID_CATEGORIA = CAT.IDCATEGORIA
GROUP BY CAT.NOME
ORDER BY TOTAL_VENDIDO DESC;
GO

-- TOTAL VENDIDO POR CIDADE

SELECT 
    E.CIDADE,
    E.ESTADO,
    SUM(N.TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C
    ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY 
    E.CIDADE,
    E.ESTADO
ORDER BY FATURAMENTO DESC;
GO
    
--  TOTAL DE VENDAS POR VENDEDOR

SELECT 
    V.NOME AS VENDEDOR,
    COUNT(N.IDNOTA) AS QTD_VENDAS,
    SUM(N.TOTAL) AS FATURAMENTO_TOTAL
FROM NOTA_FISCAL N
INNER JOIN VENDEDOR V
    ON N.ID_VENDEDOR = V.IDVENDEDOR
GROUP BY V.NOME
ORDER BY FATURAMENTO_TOTAL DESC;
GO
    
--  CONFERÊNCIA: TOTAL DA NOTA X SOMA DOS ITENS

SELECT 
    N.IDNOTA,
    N.TOTAL AS TOTAL_NOTA,
    SUM(I.TOTAL) AS TOTAL_ITENS,
    N.TOTAL - SUM(I.TOTAL) AS DIFERENCA
FROM NOTA_FISCAL N
INNER JOIN ITEM_NOTA I
    ON N.IDNOTA = I.ID_NOTA_FISCAL
GROUP BY 
    N.IDNOTA,
    N.TOTAL
ORDER BY N.IDNOTA;
GO
