-- ANÁLISE DE FATURAMENTO

USE COMERCIO;
GO
    
-- 1) FATURAMENTO TOTAL

SELECT 
    SUM(TOTAL) AS FATURAMENTO_TOTAL
FROM NOTA_FISCAL;
GO
    
-- 2) FATURAMENTO POR MÊS

SELECT 
    YEAR(DATA) AS ANO,
    MONTH(DATA) AS MES,
    SUM(TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL
GROUP BY 
    YEAR(DATA),
    MONTH(DATA)
ORDER BY ANO, MES;
GO

-- 3) FATURAMENTO POR ANO

SELECT 
    YEAR(DATA) AS ANO,
    SUM(TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL
GROUP BY YEAR(DATA)
ORDER BY ANO;
GO

-- 4) TICKET MÉDIO

SELECT 
    AVG(TOTAL) AS TICKET_MEDIO
FROM NOTA_FISCAL;
GO

-- 5) FATURAMENTO ACUMULADO NO TEMPO

SELECT 
    DATA,
    SUM(TOTAL) OVER (
        ORDER BY DATA 
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS FATURAMENTO_ACUMULADO
FROM NOTA_FISCAL
ORDER BY DATA;
GO

-- 6) VARIAÇÃO DE FATURAMENTO (MÊS A MÊS)

WITH FATURAMENTO_MENSAL AS (
    SELECT 
        DATEFROMPARTS(YEAR(DATA), MONTH(DATA), 1) AS MES,
        SUM(TOTAL) AS FATURAMENTO
    FROM NOTA_FISCAL
    GROUP BY 
        YEAR(DATA),
        MONTH(DATA)
)
SELECT 
    MES,
    FATURAMENTO,
    LAG(FATURAMENTO) OVER (ORDER BY MES) AS FATURAMENTO_ANTERIOR,
    FATURAMENTO - LAG(FATURAMENTO) OVER (ORDER BY MES) AS VARIACAO
FROM FATURAMENTO_MENSAL;
GO
    
-- 7) CRESCIMENTO PERCENTUAL

WITH FATURAMENTO_MENSAL AS (
    SELECT 
        DATEFROMPARTS(YEAR(DATA), MONTH(DATA), 1) AS MES,
        SUM(TOTAL) AS FATURAMENTO
    FROM NOTA_FISCAL
    GROUP BY 
        YEAR(DATA),
        MONTH(DATA)
)
SELECT 
    MES,
    FATURAMENTO,
    LAG(FATURAMENTO) OVER (ORDER BY MES) AS FATURAMENTO_ANTERIOR,
    CASE 
        WHEN LAG(FATURAMENTO) OVER (ORDER BY MES) = 0 THEN NULL

  
        ELSE 
            (FATURAMENTO - LAG(FATURAMENTO) OVER (ORDER BY MES)) * 100.0
            / LAG(FATURAMENTO) OVER (ORDER BY MES)
    END AS CRESCIMENTO_PERCENTUAL
FROM FATURAMENTO_MENSAL;
GO
  

-- 8) FATURAMENTO POR DIA

SELECT 
    DATA,
    SUM(TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL
GROUP BY DATA
ORDER BY DATA;
GO
    
-- 9) TOP DIAS DE FATURAMENTO

SELECT TOP 5
    DATA,
    SUM(TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL
GROUP BY DATA
ORDER BY FATURAMENTO DESC;
GO
    
-- 10) FATURAMENTO POR FORMA DE PAGAMENTO

SELECT 
    FP.FORMA,
    SUM(N.TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL N
INNER JOIN FORMA_PAGAMENTO FP
    ON N.ID_FORMA = FP.IDFORMA
GROUP BY FP.FORMA
ORDER BY FATURAMENTO DESC;
GO
    
-- 11) FATURAMENTO POR REGIÃO

SELECT 
    E.REGIAO,
    SUM(N.TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C
    ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY E.REGIAO
ORDER BY FATURAMENTO DESC;
GO
    
-- 12) TICKET MÉDIO POR MÊS

SELECT 
    YEAR(DATA) AS ANO,
    MONTH(DATA) AS MES,
    AVG(TOTAL) AS TICKET_MEDIO
FROM NOTA_FISCAL
GROUP BY 
    YEAR(DATA),
    MONTH(DATA)
ORDER BY ANO, MES;
GO
