-- ANÁLISE DE PRODUTOS

USE COMERCIO;
GO
    
-- 1) PRODUTOS MAIS VENDIDOS (POR FATURAMENTO)

SELECT 
    P.PRODUTO,
    SUM(I.TOTAL) AS FATURAMENTO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY P.PRODUTO
ORDER BY FATURAMENTO DESC;
GO
    
-- 2) PRODUTOS MAIS VENDIDOS (POR QUANTIDADE)

SELECT 
    P.PRODUTO,
    SUM(I.QUANTIDADE) AS QUANTIDADE_VENDIDA
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY P.PRODUTO
ORDER BY QUANTIDADE_VENDIDA DESC;
GO
    
-- 3) TOP 5 PRODUTOS POR FATURAMENTO

SELECT TOP 5
    P.PRODUTO,
    SUM(I.TOTAL) AS FATURAMENTO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY P.PRODUTO
ORDER BY FATURAMENTO DESC;
GO
    
-- 4) PRODUTOS COM MENOR DESEMPENHO

SELECT TOP 5
    P.PRODUTO,
    SUM(I.TOTAL) AS FATURAMENTO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY P.PRODUTO
ORDER BY FATURAMENTO ASC;
GO
    
-- 5) FATURAMENTO POR CATEGORIA

SELECT 
    C.NOME AS CATEGORIA,
    SUM(I.TOTAL) AS FATURAMENTO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY FATURAMENTO DESC;
GO
    
-- 6) PARTICIPAÇÃO DE CADA PRODUTO NO TOTAL

SELECT 
    P.PRODUTO,
    SUM(I.TOTAL) AS FATURAMENTO,
    SUM(I.TOTAL) * 100.0 / SUM(SUM(I.TOTAL)) OVER () AS PARTICIPACAO_PERCENTUAL
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY P.PRODUTO
ORDER BY FATURAMENTO DESC;
GO
    
-- 7) TICKET MÉDIO POR PRODUTO

SELECT 
    P.PRODUTO,
    AVG(I.TOTAL) AS TICKET_MEDIO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY P.PRODUTO
ORDER BY TICKET_MEDIO DESC;
GO
    
-- 8) PRODUTOS MAIS VENDIDOS POR MÊS

SELECT 
    YEAR(N.DATA) AS ANO,
    MONTH(N.DATA) AS MES,
    P.PRODUTO,
    SUM(I.TOTAL) AS FATURAMENTO
FROM ITEM_NOTA I
INNER JOIN NOTA_FISCAL N
    ON I.ID_NOTA_FISCAL = N.IDNOTA
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY 
    YEAR(N.DATA),
    MONTH(N.DATA),
    P.PRODUTO
ORDER BY ANO, MES, FATURAMENTO DESC;
GO
    
-- 9) PRODUTOS COM MAIOR LUCRO

SELECT 
    P.PRODUTO,
    SUM(I.TOTAL - (I.QUANTIDADE * P.CUSTO_MEDIO)) AS LUCRO_TOTAL
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY P.PRODUTO
ORDER BY LUCRO_TOTAL DESC;
GO
    
-- 10) PRODUTOS COM MENOR LUCRO

SELECT TOP 5
    P.PRODUTO,
    SUM(I.TOTAL - (I.QUANTIDADE * P.CUSTO_MEDIO)) AS LUCRO_TOTAL
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY P.PRODUTO
ORDER BY LUCRO_TOTAL ASC;
GO
    
-- 11) PRODUTOS SEM VENDA

SELECT 
    P.PRODUTO
FROM PRODUTO P
LEFT JOIN ITEM_NOTA I
    ON P.IDPRODUTO = I.ID_PRODUTO
WHERE I.ID_PRODUTO IS NULL;
GO
    
-- 12) PRODUTO MAIS VENDIDO (GERAL)

SELECT TOP 1
    P.PRODUTO,
    SUM(I.QUANTIDADE) AS TOTAL_VENDIDO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY P.PRODUTO
ORDER BY TOTAL_VENDIDO DESC;
GO
