-- ANÁLISE DE CLIENTES

USE COMERCIO;
GO
-- 1) TOTAL DE CLIENTES
  
SELECT COUNT(*) AS TOTAL_CLIENTES
FROM CLIENTE;
GO
  
-- 2) CLIENTES ATIVOS 

SELECT COUNT(DISTINCT ID_CLIENTE) AS CLIENTES_ATIVOS
FROM NOTA_FISCAL;
GO
  
-- 3) CLIENTES INATIVOS 

SELECT 
    C.IDCLIENTE,
    C.NOME
FROM CLIENTE C
LEFT JOIN NOTA_FISCAL N
    ON C.IDCLIENTE = N.ID_CLIENTE
WHERE N.ID_CLIENTE IS NULL;
GO
  
-- 4) TOTAL GASTO POR CLIENTE

SELECT 
    C.NOME + ' ' + C.SOBRENOME AS CLIENTE,
    SUM(N.TOTAL) AS TOTAL_GASTO
FROM CLIENTE C
INNER JOIN NOTA_FISCAL N
    ON C.IDCLIENTE = N.ID_CLIENTE
GROUP BY C.NOME, C.SOBRENOME
ORDER BY TOTAL_GASTO DESC;
GO
  
-- 5) TOP 5 CLIENTES

SELECT TOP 5
    C.NOME + ' ' + C.SOBRENOME AS CLIENTE,
    SUM(N.TOTAL) AS TOTAL_GASTO
FROM CLIENTE C
INNER JOIN NOTA_FISCAL N
    ON C.IDCLIENTE = N.ID_CLIENTE
GROUP BY C.NOME, C.SOBRENOME
ORDER BY TOTAL_GASTO DESC;
GO
  
-- 6) CLIENTES QUE MAIS COMPRARAM 

SELECT TOP 5
    C.NOME + ' ' + C.SOBRENOME AS CLIENTE,
    COUNT(N.IDNOTA) AS QTD_COMPRAS
FROM CLIENTE C
INNER JOIN NOTA_FISCAL N
    ON C.IDCLIENTE = N.ID_CLIENTE
GROUP BY C.NOME, C.SOBRENOME
ORDER BY QTD_COMPRAS DESC;
GO
  
-- 7) TICKET MÉDIO POR CLIENTE

SELECT 
    C.NOME + ' ' + C.SOBRENOME AS CLIENTE,
    AVG(N.TOTAL) AS TICKET_MEDIO
FROM CLIENTE C
INNER JOIN NOTA_FISCAL N
    ON C.IDCLIENTE = N.ID_CLIENTE
GROUP BY C.NOME, C.SOBRENOME
ORDER BY TICKET_MEDIO DESC;
GO
  
-- 8) DATA DA PRIMEIRA COMPRA

SELECT 
    C.NOME + ' ' + C.SOBRENOME AS CLIENTE,
    MIN(N.DATA) AS PRIMEIRA_COMPRA
FROM CLIENTE C
INNER JOIN NOTA_FISCAL N
    ON C.IDCLIENTE = N.ID_CLIENTE
GROUP BY C.NOME, C.SOBRENOME;
GO
  
-- 9) DATA DA ÚLTIMA COMPRA

SELECT 
    C.NOME + ' ' + C.SOBRENOME AS CLIENTE,
    MAX(N.DATA) AS ULTIMA_COMPRA
FROM CLIENTE C
INNER JOIN NOTA_FISCAL N
    ON C.IDCLIENTE = N.ID_CLIENTE
GROUP BY C.NOME, C.SOBRENOME;
GO
  
-- 10) CLIENTES QUE NÃO COMPRAM HÁ MAIS DE 30 DIAS

SELECT 
    C.NOME + ' ' + C.SOBRENOME AS CLIENTE,
    MAX(N.DATA) AS ULTIMA_COMPRA
FROM CLIENTE C
INNER JOIN NOTA_FISCAL N
    ON C.IDCLIENTE = N.ID_CLIENTE
GROUP BY C.NOME, C.SOBRENOME
HAVING MAX(N.DATA) < DATEADD(DAY, -30, GETDATE());
GO
  
-- 11) NOVOS CLIENTES POR MÊS
  
SELECT 
    YEAR(PRIMEIRA_COMPRA) AS ANO,
    MONTH(PRIMEIRA_COMPRA) AS MES,
    COUNT(*) AS NOVOS_CLIENTES
FROM (
    SELECT 
        ID_CLIENTE,
        MIN(DATA) AS PRIMEIRA_COMPRA
    FROM NOTA_FISCAL
    GROUP BY ID_CLIENTE
) T
GROUP BY 
    YEAR(PRIMEIRA_COMPRA),
    MONTH(PRIMEIRA_COMPRA)
ORDER BY ANO, MES;
GO
  
-- 12) CLIENTES RECORRENTES 

SELECT 
    C.NOME + ' ' + C.SOBRENOME AS CLIENTE,
    COUNT(N.IDNOTA) AS QTD_COMPRAS
FROM CLIENTE C
INNER JOIN NOTA_FISCAL N
    ON C.IDCLIENTE = N.ID_CLIENTE
GROUP BY C.NOME, C.SOBRENOME
HAVING COUNT(N.IDNOTA) > 1
ORDER BY QTD_COMPRAS DESC;
GO
