-- ANÁLISE DE CATEGORIAS

USE COMERCIO;
GO
  
-- 1) FATURAMENTO POR CATEGORIA

SELECT 
    C.NOME AS CATEGORIA,
    SUM(I.TOTAL) AS FATURAMENTO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY FATURAMENTO DESC;
GO
  
-- 2) QUANTIDADE VENDIDA POR CATEGORIA

SELECT 
    C.NOME AS CATEGORIA,
    SUM(I.QUANTIDADE) AS QUANTIDADE_VENDIDA
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY QUANTIDADE_VENDIDA DESC;
GO
  
-- 3) TICKET MÉDIO POR CATEGORIA

SELECT 
    C.NOME AS CATEGORIA,
    AVG(I.TOTAL) AS TICKET_MEDIO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY TICKET_MEDIO DESC;
GO
  
-- 4) PARTICIPAÇÃO DE CADA CATEGORIA

SELECT 
    C.NOME AS CATEGORIA,
    SUM(I.TOTAL) AS FATURAMENTO,
    SUM(I.TOTAL) * 100.0 / SUM(SUM(I.TOTAL)) OVER () AS PARTICIPACAO_PERCENTUAL
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY FATURAMENTO DESC;
GO
  
-- 5) TOP CATEGORIAS

SELECT TOP 3
    C.NOME AS CATEGORIA,
    SUM(I.TOTAL) AS FATURAMENTO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY FATURAMENTO DESC;
GO
  
-- 6) CATEGORIAS COM MENOR DESEMPENHO

SELECT TOP 3
    C.NOME AS CATEGORIA,
    SUM(I.TOTAL) AS FATURAMENTO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY FATURAMENTO ASC;
GO
  
-- 7) CATEGORIAS SEM VENDA

SELECT 
    C.NOME AS CATEGORIA
FROM CATEGORIA C
LEFT JOIN PRODUTO P
    ON C.IDCATEGORIA = P.ID_CATEGORIA
LEFT JOIN ITEM_NOTA I
    ON P.IDPRODUTO = I.ID_PRODUTO
WHERE I.ID_PRODUTO IS NULL;
GO
  
-- 8) FATURAMENTO POR CATEGORIA POR MÊS

SELECT 
    YEAR(N.DATA) AS ANO,
    MONTH(N.DATA) AS MES,
    C.NOME AS CATEGORIA,
    SUM(I.TOTAL) AS FATURAMENTO
FROM ITEM_NOTA I
INNER JOIN NOTA_FISCAL N
    ON I.ID_NOTA_FISCAL = N.IDNOTA
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY 
    YEAR(N.DATA),
    MONTH(N.DATA),
    C.NOME
ORDER BY ANO, MES, FATURAMENTO DESC;
GO
  
-- 9) CATEGORIA MAIS VENDIDA

SELECT TOP 1
    C.NOME AS CATEGORIA,
    SUM(I.QUANTIDADE) AS TOTAL_VENDIDO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY TOTAL_VENDIDO DESC;
GO
  
-- 10) LUCRO POR CATEGORIA

SELECT 
    C.NOME AS CATEGORIA,
    SUM(I.TOTAL - (I.QUANTIDADE * P.CUSTO_MEDIO)) AS LUCRO
FROM ITEM_NOTA I
INNER JOIN PRODUTO P
    ON I.ID_PRODUTO = P.IDPRODUTO
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY LUCRO DESC;
GO
  
-- 11) MÉDIA DE PREÇO POR CATEGORIA

SELECT 
    C.NOME AS CATEGORIA,
    AVG(P.VALOR) AS PRECO_MEDIO
FROM PRODUTO P
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY PRECO_MEDIO DESC;
GO
  
-- 12) QUANTIDADE DE PRODUTOS POR CATEGORIA

SELECT 
    C.NOME AS CATEGORIA,
    COUNT(P.IDPRODUTO) AS QTD_PRODUTOS
FROM PRODUTO P
INNER JOIN CATEGORIA C
    ON P.ID_CATEGORIA = C.IDCATEGORIA
GROUP BY C.NOME
ORDER BY QTD_PRODUTOS DESC;
GO
