-- ANÁLISE GEOGRÁFICA

USE COMERCIO;
GO
  
-- 1) FATURAMENTO POR CIDADE

SELECT 
    E.CIDADE,
    E.ESTADO,
    SUM(N.TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C
    ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY 
    E.CIDADE,
    E.ESTADO
ORDER BY FATURAMENTO DESC;
GO
  
-- 2) TOP 10 CIDADES

SELECT TOP 10
    E.CIDADE,
    E.ESTADO,
    SUM(N.TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C
    ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY 
    E.CIDADE,
    E.ESTADO
ORDER BY FATURAMENTO DESC;
GO
  
-- 3) FATURAMENTO POR ESTADO

SELECT 
    E.ESTADO,
    SUM(N.TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C
    ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY E.ESTADO
ORDER BY FATURAMENTO DESC;
GO
  
-- 4) FATURAMENTO POR REGIÃO

SELECT 
    E.REGIAO,
    SUM(N.TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C
    ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY E.REGIAO
ORDER BY FATURAMENTO DESC;
GO
  
-- 5) QUANTIDADE DE VENDAS POR CIDADE

SELECT 
    E.CIDADE,
    COUNT(N.IDNOTA) AS QTD_VENDAS
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C
    ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY E.CIDADE
ORDER BY QTD_VENDAS DESC;
GO
  
-- 6) TICKET MÉDIO POR CIDADE

SELECT 
    E.CIDADE,
    AVG(N.TOTAL) AS TICKET_MEDIO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C
    ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY E.CIDADE
ORDER BY TICKET_MEDIO DESC;
GO
  
-- 7) CIDADES COM MAIOR CRESCIMENTO 

WITH FATURAMENTO_MENSAL AS (
    SELECT 
        E.CIDADE,
        DATEFROMPARTS(YEAR(N.DATA), MONTH(N.DATA), 1) AS MES,
        SUM(N.TOTAL) AS FATURAMENTO
    FROM NOTA_FISCAL N
    INNER JOIN CLIENTE C ON N.ID_CLIENTE = C.IDCLIENTE
    INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
    GROUP BY 
        E.CIDADE,
        YEAR(N.DATA),
        MONTH(N.DATA)
)
SELECT 
    CIDADE,
    MES,
    FATURAMENTO,
    LAG(FATURAMENTO) OVER (PARTITION BY CIDADE ORDER BY MES) AS FATURAMENTO_ANTERIOR
FROM FATURAMENTO_MENSAL;
GO
  
-- 8) PARTICIPAÇÃO DE CADA CIDADE

SELECT 
    E.CIDADE,
    SUM(N.TOTAL) AS FATURAMENTO,
    SUM(N.TOTAL) * 100.0 / SUM(SUM(N.TOTAL)) OVER () AS PARTICIPACAO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY E.CIDADE
ORDER BY FATURAMENTO DESC;
GO
  
-- 9) CIDADES SEM VENDA

SELECT 
    DISTINCT E.CIDADE
FROM ENDERECO E
LEFT JOIN CLIENTE C ON E.ID_CLIENTE = C.IDCLIENTE
LEFT JOIN NOTA_FISCAL N ON C.IDCLIENTE = N.ID_CLIENTE
WHERE N.ID_CLIENTE IS NULL;
GO
  
-- 10) FATURAMENTO POR CIDADE POR ANO

SELECT 
    YEAR(N.DATA) AS ANO,
    E.CIDADE,
    SUM(N.TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY YEAR(N.DATA), E.CIDADE
ORDER BY ANO, FATURAMENTO DESC;
GO
  
-- 11) TOP CIDADE POR FATURAMENTO

SELECT TOP 1
    E.CIDADE,
    SUM(N.TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY E.CIDADE
ORDER BY FATURAMENTO DESC;
GO
  
-- 12) ESTADO COM MAIOR FATURAMENTO

SELECT TOP 1
    E.ESTADO,
    SUM(N.TOTAL) AS FATURAMENTO
FROM NOTA_FISCAL N
INNER JOIN CLIENTE C ON N.ID_CLIENTE = C.IDCLIENTE
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
GROUP BY E.ESTADO
ORDER BY FATURAMENTO DESC;
GO
